# Generated by Django 5.0 on 2024-04-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_customer_alter_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
    ]
