# Generated by Django 5.0 on 2024-04-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_product_price_product_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, max_length=100000000, null=True),
        ),
    ]
